anaconda-init: always mount /LiveOS/rootfs.img
The /LiveOS/rootfs.img is used for the image based installation, we only mount
it when "liveinst" in the past, but it didn't work for the kickstart
installation, since the command for kickstart installation is:

CMDLINE="kickstart"
/etc/anaconda-init start

The livimg information is recorded in the ks file, we need add an extra option
to make it work if we don't mount it:
CMDLINE="kickstart liveinst"

This seems not a good idea, we can alwasy mount it to fix the problem.

[WIND: US21002]

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>

diff --git a/recipes-installer/anaconda-init/anaconda-init/anaconda-init b/recipes-installer/anaconda-init/anaconda-init/anaconda-init
--- a/recipes-installer/anaconda-init/anaconda-init/anaconda-init
+++ b/recipes-installer/anaconda-init/anaconda-init/anaconda-init
@@ -156,10 +156,18 @@ FOE
            anaconda_opts="$anaconda_opts --kickstart=file:///run/initramfs/live/ks.cfg"
        fi
 
-       if [ -n "$liveinst" ]; then
+       ROOT_IMAGE="/LiveOS/rootfs.img"
+       if [ -e $ROOT_IMAGE ]; then
            mkdir -p /mnt/target_rootfs
-           mount -o loop=/dev/loop3 /LiveOS/rootfs.img /mnt/target_rootfs
-           anaconda_opts="$anaconda_opts --liveinst --method=liveinst:/dev/loop3"
+           mount -o loop=/dev/loop3 $ROOT_IMAGE /mnt/target_rootfs
+           [ $? -eq 0 ] || exit 1
+       fi
+       if [ -n "$liveinst" ]; then
+           if [ ! -e $ROOT_IMAGE ]; then
+               echo "ERROR: no $ROOT_IMAGE" >&2
+           else
+               anaconda_opts="$anaconda_opts --liveinst --method=liveinst:/dev/loop3"
+           fi
        fi
 
        BOOTIF=`cat /proc/cmdline |xargs -n1 echo |grep BOOTIF=`
